### ISSUE TITLE
Maker edition issue

### ISSUE THREAD

**Issue by EverybodyElse** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#7]
After adding the modl to Ignition make and adding the palette to node red, when I try to read or write tags I get the following response.

JSON error: SyntaxError: Unexpected end of JSON input

It doesn't looks like I'm alone either:
- https://forum.inductiveautomation.com/t/node-red-for-maker/36371
- https://youtu.be/rSBT2EKk7fo

Any suggestions on what may be causing this?

**Comment by iatraviscox** [comment]
Sorry for taking a bit to get back to you. I found the problem. I intended on updating both the Ignition module and the Node-RED nodes but I only published the new module. I didn't publish the new version of the nodes. There was a very simple change in the nodes to POST to the correct endpoint in Ignition, since that changed slightly in version 8. I had it working on my local copy. I have now published, correctly, a new version of the nodes to version 1.5.6. You can go into Node-RED's palette and update your nodes to the latest version and it will work.

[node-red-contrib-ignition-nodes](https://flows.nodered.org/node/node-red-contrib-ignition-nodes)

**Comment by EverybodyElse** [comment]
Tested and working. Thanks for the update!
